version: '2'
services:
  openDirectory:
    image: caloldur/tls-open-directory
    container_name: open-directory-service
    ports:
      - "44431:44431"
    restart: always
    environment:
      - TOD_SERVER_ADDRESS=0.0.0.0
      - TOD_PORT=44431
      - TOD_DATA_DIRECTORY=/data
      - TOD_CERT_FILE=/ssl/fullchain.pem
      - TOD_KEY_FILE=/ssl/privatekey.pem
    volumes:
      - /data/containers/storage/opendir:/data
      - /data/containers/storage/certs:/ssl
